services:
  app:
    build:
      target: runner
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      ANTHROPIC_API_KEY: ${SKILLAI_ANTHROPIC_API_KEY}
  db:
    ports:
      - '5433:5432'
