#!/usr/bin/env bash
# infra/scripts/80-deploy.sh
# Deploy SkillAi to EKS using Kustomize.
#
# Steps:
#   1. Substitute image placeholders in kustomize overlay.
#   2. Apply the rendered secret (generated by 50-render-secret.sh).
#   3. kubectl apply -k infra/k8s/overlays/prod
#   4. Wait for migrate job to complete.
#   5. Wait for deployment rollout.
#   6. Print ingress URL.
#
# Idempotent — re-running updates the deployment to the current git SHA.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TF_DIR="${REPO_ROOT}/infra/terraform"
K8S_BASE="${REPO_ROOT}/infra/k8s/base"
K8S_OVERLAY="${REPO_ROOT}/infra/k8s/overlays/prod"
SECRET_FILE="${K8S_BASE}/secret.yaml"
NAMESPACE="skillai"

# shellcheck source=/dev/null
eval "$(direnv export bash 2>/dev/null)" || source "${REPO_ROOT}/.envrc"

log() { echo "[deploy] $(date -u +%H:%M:%SZ) $*"; }

command -v kubectl &>/dev/null || { echo "[deploy] ERROR: kubectl not found."; exit 1; }

# ---------------------------------------------------------------------------
# Assert rendered secret exists
# ---------------------------------------------------------------------------
if [[ ! -f "${SECRET_FILE}" ]]; then
  echo "[deploy] ERROR: ${SECRET_FILE} not found."
  echo "[deploy]        Run 50-render-secret.sh first to render the Kubernetes Secret."
  exit 1
fi

# ---------------------------------------------------------------------------
# Read Terraform outputs
# ---------------------------------------------------------------------------
if [[ ! -d "${TF_DIR}" ]]; then
  echo "[deploy] ERROR: ${TF_DIR} not found. Run 10-terraform-apply.sh first."
  exit 1
fi

cd "${TF_DIR}"
log "Reading Terraform outputs ..."
ECR_URL="$(terraform output -raw ecr_repository_url)"
cd "${REPO_ROOT}"

GIT_SHA="$(git rev-parse --short HEAD)"
IMAGE_TAG="${ECR_URL}:${GIT_SHA}"
log "Deploying image: ${IMAGE_TAG}"

# ---------------------------------------------------------------------------
# Determine INGRESS_HOST from NEXTAUTH_URL
# Strips the https:// scheme to get bare hostname.
# ---------------------------------------------------------------------------
NEXTAUTH_URL="${NEXTAUTH_URL:-}"
if [[ -z "${NEXTAUTH_URL}" ]]; then
  echo "[deploy] ERROR: NEXTAUTH_URL is not set in .envrc."
  echo "[deploy]        Set it to https://<nlb-ip>.nip.io after running 30-platform-install.sh."
  exit 1
fi
INGRESS_HOST="${NEXTAUTH_URL#https://}"
INGRESS_HOST="${INGRESS_HOST#http://}"
INGRESS_HOST="${INGRESS_HOST%%/*}"
log "Ingress host: ${INGRESS_HOST}"

# ---------------------------------------------------------------------------
# Step 1 — Substitute placeholders in overlay files
# We use sed on a temporary copy of the overlay kustomization rather than
# mutating the committed file, so the overlay remains clean for git.
# Placeholders: __ECR_REPO__, __IMAGE_TAG__, __INGRESS_HOST__
# ---------------------------------------------------------------------------
log "Substituting image/ingress placeholders in kustomize overlay ..."

TMP_OVERLAY="$(mktemp -d)"
cp -r "${K8S_OVERLAY}/." "${TMP_OVERLAY}/"

# Substitute in all yaml files in the overlay
find "${TMP_OVERLAY}" -name "*.yaml" | while read -r f; do
  sed -i \
    -e "s|__ECR_REPO__|${ECR_URL}|g" \
    -e "s|__IMAGE_TAG__|${GIT_SHA}|g" \
    -e "s|__INGRESS_HOST__|${INGRESS_HOST}|g" \
    "${f}"
done

# Also substitute in the base ingress.yaml
TMP_BASE="$(mktemp -d)"
cp -r "${K8S_BASE}/." "${TMP_BASE}/"
find "${TMP_BASE}" -name "*.yaml" | while read -r f; do
  sed -i \
    -e "s|__ECR_REPO__|${ECR_URL}|g" \
    -e "s|__IMAGE_TAG__|${GIT_SHA}|g" \
    -e "s|__INGRESS_HOST__|${INGRESS_HOST}|g" \
    "${f}"
done

# Copy the rendered secret into the temp base
cp "${SECRET_FILE}" "${TMP_BASE}/secret.yaml"

# Rewrite the overlay's kustomization.yaml to point at the tmp base
sed -i "s|../../base|${TMP_BASE}|g" "${TMP_OVERLAY}/kustomization.yaml"

# ---------------------------------------------------------------------------
# Step 2 — Ensure namespace exists (idempotent)
# ---------------------------------------------------------------------------
log "Ensuring namespace '${NAMESPACE}' exists ..."
kubectl apply -f "${K8S_BASE}/namespace.yaml" 2>/dev/null || \
  kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

# ---------------------------------------------------------------------------
# Step 3 — Apply the overlay
# ---------------------------------------------------------------------------
log "Applying kustomize overlay (${K8S_OVERLAY}) ..."
kubectl apply -k "${TMP_OVERLAY}"

rm -rf "${TMP_OVERLAY}" "${TMP_BASE}"

# ---------------------------------------------------------------------------
# Shred the rendered cleartext secret so it does not outlive the deploy.
# The file contains raw API keys and DB credentials — leaving it on disk
# after apply is a credential-leak waiting to happen.
# ---------------------------------------------------------------------------
if [[ -f "${SECRET_FILE}" ]]; then
  log "Shredding rendered secret file ..."
  shred -u "${SECRET_FILE}" 2>/dev/null || rm -f "${SECRET_FILE}"
  log "Secret file removed."
fi

# ---------------------------------------------------------------------------
# Step 4 — Wait for migrate job
# The migrate Job is defined in k8s/base/migrate-job.yaml.
# It runs before the main deployment and exits when all migrations are applied.
# ---------------------------------------------------------------------------
log "Waiting for migrate job to complete (timeout 5m) ..."
if kubectl get job skillai-migrate -n "${NAMESPACE}" &>/dev/null; then
  kubectl wait job/skillai-migrate \
    --namespace="${NAMESPACE}" \
    --for=condition=complete \
    --timeout=300s \
  || {
    echo "[deploy] WARN: Migrate job did not complete in 5 minutes."
    echo "[deploy]       Check: kubectl logs job/skillai-migrate -n ${NAMESPACE}"
    echo "[deploy]       Continuing with deployment — app will crash if migrations failed."
  }
  log "Migrate job complete."
else
  log "No migrate job found — skipping job wait (first deploy or job not in this overlay)."
fi

# ---------------------------------------------------------------------------
# Step 5 — Wait for deployment rollout
# ---------------------------------------------------------------------------
log "Waiting for deployment rollout (timeout 10m) ..."
kubectl rollout status deployment/skillai-app \
  --namespace="${NAMESPACE}" \
  --timeout=600s

# ---------------------------------------------------------------------------
# Step 6 — Print ingress URL
# ---------------------------------------------------------------------------
echo ""
log "Deployment complete."
log "Application URL: https://${INGRESS_HOST}"
log ""
log "Next step: run 90-verify.sh to confirm the deployment is healthy."
kubectl get ingress -n "${NAMESPACE}" 2>/dev/null || true
