terraform {
  required_version = ">= 1.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  # Remote state — S3 backend with DynamoDB locking.
  #
  # The actual bucket/key/region/dynamodb_table values live in backend.tf,
  # which is generated by infra/scripts/05-state-bootstrap.sh.
  # Using an empty backend "s3" {} block here (partial configuration) keeps
  # this file environment-agnostic so it works across projects and regions.
  #
  # First-time setup:
  #   1. Run `infra/scripts/05-state-bootstrap.sh` ONCE to create the bucket,
  #      DynamoDB table, and write infra/terraform/backend.tf.
  #   2. Run `terraform init` (or `terraform init -migrate-state` if you have
  #      an existing local terraform.tfstate to move to S3).
  #   3. Do NOT delete local terraform.tfstate manually — let `terraform init
  #      -migrate-state` handle the copy, then delete the local copy afterwards.
  #
  # backend.tf is committed to the repo; it contains only bucket/table names,
  # not secrets.  The S3 bucket itself is encrypted (SSE-KMS) and has all
  # public access blocked.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project
      ManagedBy   = "terraform"
      Environment = "production"
    }
  }
}
